
name: avsg
version: '0.5'
summary: Uma ferramenta para criação de scripts avs.
description: |
  Cria arquivos avs sem a necessidade de conhecimentos sobre a linguagem.
grade: devel
confinement: strict

apps:
  avsg:
    plugs:
      - unity7
      - home

parts:
  avsg:
    source: .
    plugin: qmake
    qt-version: qt5
    project-files: [AVSGenerator.pro]
    build-packages:
      - build-essential
      - qt5-default
    after: [desktop-qt5]
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
